-- ============================================================
-- Massive templates seed — Profissões, Países, Esportes, Games,
-- Referências culturais, Aesthetics
-- 200+ templates novos
-- ============================================================

INSERT INTO public.templates (name, category, description, prompt, uses_count, rating, preview_url, media_type, complexity, credits_cost) VALUES

-- ═══════════════════════ PROFISSÕES (60) ═══════════════════════
('Médica Editorial', 'Professions', 'Médica em hospital moderno', 'female doctor, white coat, stethoscope, modern hospital setting, professional editorial, soft lighting', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Cirurgiã Sala', 'Professions', 'Cirurgiã em sala de cirurgia', 'female surgeon, scrubs, mask down, modern surgical room, dramatic editorial, focused', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Advogada Tribunal', 'Professions', 'Advogada em tribunal', 'female lawyer, sharp suit, courthouse, confident editorial, professional', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Professora Universidade', 'Professions', 'Professora universitária', 'female professor, academic library, blazer cardigan, intellectual editorial, warm tones', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Chef Cozinha', 'Professions', 'Chef em cozinha profissional', 'female chef, white jacket, professional kitchen, plating dish, gastronomic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Sommelier Vinícola', 'Professions', 'Sommelier degustação', 'female sommelier, wine cellar, tasting glass, elegant winery editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Arquiteta Studio', 'Professions', 'Arquiteta com plantas', 'female architect, modern studio, blueprint table, design editorial, minimal aesthetic', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Designer Gráfica', 'Professions', 'Designer com macbook', 'female graphic designer, mac studio, mood boards, creative editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Fotógrafa Profissional', 'Professions', 'Fotógrafa com câmera', 'female photographer, leica camera, urban setting, candid behind-scenes editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Engenheira Obra', 'Professions', 'Engenheira em construção', 'female engineer, hard hat, construction site, blueprint, professional editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Programadora Tech', 'Professions', 'Dev em startup', 'female software engineer, multiple monitors, modern tech office, focused editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('CEO Executiva', 'Professions', 'CEO em sala de reunião', 'female CEO, power suit, corner office skyline view, executive editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Investidora Wall Street', 'Professions', 'Investidora bolsa de valores', 'female investor, financial district, trading screens, power editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Jornalista Reportagem', 'Professions', 'Jornalista em campo', 'female journalist, microphone, breaking news scene, dynamic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Apresentadora TV', 'Professions', 'Apresentadora estúdio', 'female TV host, studio lights, professional set, broadcasting editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Atriz Set Filme', 'Professions', 'Atriz no set', 'actress on movie set, vintage hollywood, dramatic lighting, behind scenes editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Cantora Stage', 'Professions', 'Cantora no palco', 'female singer, stage performance, microphone, concert lighting, dynamic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('DJ Festa', 'Professions', 'DJ tocando festa', 'female DJ booth, headphones, neon lights, electronic music festival, dynamic', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Bailarina Ballet', 'Professions', 'Bailarina ballet', 'female ballerina, tutu, opera house stage, en pointe, classical elegance editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Coreógrafa Studio', 'Professions', 'Coreógrafa de dança', 'female choreographer, dance studio, instructing pose, athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Estilista Atelier', 'Professions', 'Estilista no atelier', 'female fashion designer, atelier, sewing, creative process editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Make-up Artist Backstage', 'Professions', 'Make artist backstage', 'female makeup artist, backstage, brushes, fashion week editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Cabeleireira Salão', 'Professions', 'Cabeleireira em salão', 'female hairstylist, modern salon, scissors, professional editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Influencer Studio', 'Professions', 'Influencer ring light', 'female influencer, ring light, content creation studio, vlogger editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Personal Trainer', 'Professions', 'Personal academia', 'female personal trainer, athletic wear, gym, motivating client, fitness editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Yoga Instructor', 'Professions', 'Instrutora yoga retreat', 'female yoga instructor, retreat setting, asana pose, wellness editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Nutricionista Office', 'Professions', 'Nutricionista consultório', 'female nutritionist, modern office, healthy food display, wellness editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Psicóloga Consultório', 'Professions', 'Psicóloga atendimento', 'female psychologist, cozy office, listening, empathetic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Veterinária Clínica', 'Professions', 'Veterinária com pet', 'female veterinarian, examining puppy, modern clinic, caring editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Dentista Consultório', 'Professions', 'Dentista atendendo', 'female dentist, white coat, modern dental office, professional editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Enfermeira Hospital', 'Professions', 'Enfermeira plantão', 'female nurse, scrubs, hospital corridor, dedicated editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Bombeira Heroína', 'Professions', 'Bombeira em ação', 'female firefighter, gear uniform, fire truck, heroic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Policial Federal', 'Professions', 'Policial uniforme', 'female police officer, professional uniform, urban background, authority editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Militar Patente', 'Professions', 'Militar uniforme', 'female military officer, dress uniform, formal military editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Piloto Avião', 'Professions', 'Piloto cabine de comando', 'female pilot, captain uniform, cockpit, aviation editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Comissária Bordo', 'Professions', 'Comissária aeroporto', 'female flight attendant, airline uniform, airport, glamorous travel editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Marinheira Yacht', 'Professions', 'Marinheira em iate', 'female sailor, nautical outfit, luxury yacht, coastal editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Astronauta Espacial', 'Professions', 'Astronauta missão', 'female astronaut, spacesuit, space station, sci-fi editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Cientista Lab', 'Professions', 'Cientista laboratório', 'female scientist, lab coat, microscope, research lab editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Bióloga Marinha', 'Professions', 'Bióloga oceano', 'female marine biologist, scuba gear, coral reef, underwater editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Arqueóloga Sítio', 'Professions', 'Arqueóloga descoberta', 'female archaeologist, excavation site, dusty notebook, indiana jones editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Bibliotecária Estante', 'Professions', 'Bibliotecária acervo', 'female librarian, vintage library, glasses, books, dark academia editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Pintora Ateliê', 'Professions', 'Pintora estúdio arte', 'female painter, art studio, canvas, paint splatters, creative editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Escritora Café', 'Professions', 'Escritora trabalhando', 'female writer, vintage typewriter, coffee shop, intellectual editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Tatuadora Estúdio', 'Professions', 'Tatuadora trabalhando', 'female tattoo artist, edgy studio, tattooing, alternative editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Florista Loja', 'Professions', 'Florista botânica', 'female florist, lush flower shop, arranging bouquet, natural editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Padeira Fornada', 'Professions', 'Padeira artesanal', 'female baker, artisan bakery, fresh bread, warm rustic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Barista Café', 'Professions', 'Barista latte art', 'female barista, specialty coffee shop, latte art, third-wave editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Bartender Coquetelaria', 'Professions', 'Bartender preparando drink', 'female bartender, speakeasy bar, mixology, dim moody editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Surfista Pro', 'Professions', 'Surfista profissional', 'female pro surfer, surfboard beach, athletic ocean editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Skatista Pista', 'Professions', 'Skatista profissional', 'female pro skateboarder, skate park, urban athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Fazendeira Rural', 'Professions', 'Fazendeira no campo', 'female farmer, rural setting, denim overall, sunny pastoral editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Jardineira Botânica', 'Professions', 'Jardineira terraço', 'female gardener, urban rooftop garden, natural earthy editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Sommelier Café', 'Professions', 'Especialista em café', 'female coffee specialist, cupping, third-wave aesthetic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Cosplay Profissional', 'Professions', 'Cosplayer profissional', 'female cosplayer, anime convention, detailed costume, vibrant editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Streamer Setup', 'Professions', 'Streamer twitch setup', 'female gamer streamer, RGB setup, headset, gaming editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Gamer eSports', 'Professions', 'Pro player eSports', 'female pro gamer, esports arena, jersey, competitive editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Modelo Runway Pro', 'Professions', 'Modelo passarela', 'female runway model, fashion week, designer dress, dramatic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Coach Motivacional', 'Professions', 'Coach palestra', 'female speaker, TED stage, microphone, inspiring editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Empreendedora Tech', 'Professions', 'Founder startup', 'female tech founder, trendy office, hoodie + macbook, startup editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Real Estate Agent', 'Professions', 'Corretora luxo', 'female real estate agent, luxury property, blazer, professional editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),

-- ═══════════════════════ PAÍSES (40) ═══════════════════════
('Brasil — Salvador', 'Countries', 'Salvador Pelourinho', 'salvador bahia pelourinho, colonial colorful, capoeira street, brazilian cultural editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Brasil — Amazônia', 'Countries', 'Amazônia floresta', 'amazon rainforest brazil, indigenous culture, river boat, exotic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Brasil — Pantanal', 'Countries', 'Pantanal natural', 'pantanal brazil wildlife, capybara, sunset wetlands, eco editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Brasil — Chapada', 'Countries', 'Chapada Diamantina', 'chapada diamantina bahia, waterfall, hiking, adventure editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Brasil — Lençóis MA', 'Countries', 'Lençóis Maranhenses', 'lencois maranhenses dunes, blue lagoon, surreal landscape editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Argentina — Buenos Aires', 'Countries', 'Tango Buenos Aires', 'buenos aires tango, la boca colorful, argentine cultural editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Chile — Atacama', 'Countries', 'Deserto Atacama', 'atacama desert chile, salt flats, surreal landscape, adventure editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Peru — Machu Picchu', 'Countries', 'Machu Picchu Inca', 'machu picchu peru, ancient inca ruins, llama, andean editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Colombia — Cartagena', 'Countries', 'Cartagena colonial', 'cartagena colombia, colorful colonial streets, latin caribbean editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('México — Cidade do México', 'Countries', 'CDMX colorida', 'mexico city, colorful coyoacan, frida kahlo aesthetic, vibrant editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Cuba — Havana', 'Countries', 'Havana retrô', 'havana cuba, vintage cars, colorful colonial, malecon, retro editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('USA — Nova York', 'Countries', 'Manhattan skyline', 'new york manhattan skyline, yellow taxi, urban energy editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('USA — Miami Beach', 'Countries', 'Miami art deco', 'miami south beach, art deco, neon, latin tropical editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('USA — Texas Cowboy', 'Countries', 'Texas western', 'texas western style, cowboy hat, ranch, americana editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('USA — Hawaii', 'Countries', 'Hawaii vulcão', 'hawaii volcano beach, tropical paradise, hula editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Canadá — Banff', 'Countries', 'Banff Rocky Mountains', 'banff canada, rocky mountains, lake louise turquoise, alpine editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Reino Unido — Londres', 'Countries', 'Londres icônica', 'london iconic, big ben, red phone booth, british classic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Escócia — Highlands', 'Countries', 'Highlands escocês', 'scotland highlands, misty moors, rugged castle, celtic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Irlanda — Dublin', 'Countries', 'Dublin pubs', 'dublin ireland, traditional pub, green countryside, celtic charm editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Alemanha — Berlim', 'Countries', 'Berlim techno', 'berlin germany, brandenburg gate, techno club aesthetic, edgy editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Holanda — Amsterdam', 'Countries', 'Amsterdam canal', 'amsterdam canals, bicycles, dutch architecture, charming editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Áustria — Salzburg', 'Countries', 'Salzburg Mozart', 'salzburg austria, baroque architecture, alpine charm, classical editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Suíça — Zermatt', 'Countries', 'Zermatt Matterhorn', 'zermatt swiss alps, matterhorn, ski resort, alpine luxury editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Itália — Veneza', 'Countries', 'Veneza gôndola', 'venice italy, gondola canal, renaissance romance editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Itália — Roma', 'Countries', 'Roma Coliseu', 'rome italy colosseum, ancient ruins, vespa, dolce vita editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Espanha — Barcelona', 'Countries', 'Barcelona Gaudí', 'barcelona gaudi park, mediterranean spanish editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Espanha — Sevilla', 'Countries', 'Sevilla flamenco', 'seville spain, flamenco, andalusian colorful, passionate editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Portugal — Lisboa', 'Countries', 'Lisboa azulejos', 'lisbon portugal, yellow tram, blue azulejos, romantic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Grécia — Mykonos', 'Countries', 'Mykonos festas', 'mykonos greece, white blue architecture, beach club, hellenic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Turquia — Capadócia', 'Countries', 'Cappadocia balões', 'cappadocia turkey hot air balloons sunrise, fairy chimneys, magical editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Egito — Pirâmides', 'Countries', 'Pirâmides Gizé', 'egypt giza pyramids, golden desert, ancient civilization editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Marrocos — Chefchaouen', 'Countries', 'Chefchaouen azul', 'chefchaouen morocco blue city, alleys, exotic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Quênia — Safari Maasai', 'Countries', 'Safari maasai', 'kenya maasai mara safari, jeep, savanna sunset, wildlife editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('África do Sul — Cape Town', 'Countries', 'Cape Town Table Mountain', 'cape town south africa, table mountain, ocean drive editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Índia — Taj Mahal', 'Countries', 'Taj Mahal Agra', 'india agra taj mahal, sari, marble palace, royal editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('China — Pequim', 'Countries', 'Pequim Muralha', 'china great wall beijing, ancient architecture, cultural editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Coreia do Sul — Seoul', 'Countries', 'Seoul Gangnam', 'seoul gangnam korea, k-pop modern, neon street fashion editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Tailândia — Bangkok', 'Countries', 'Bangkok templo', 'bangkok thailand, ornate temple, tuk tuk, vibrant exotic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Filipinas — Palawan', 'Countries', 'Palawan paraíso', 'palawan philippines, lagoon, kayak paradise, tropical editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Austrália — Sydney', 'Countries', 'Sydney Opera', 'sydney australia opera house, harbour bridge, modern editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),

-- ═══════════════════════ ESPORTES (35) ═══════════════════════
('Boxe Treino', 'Sports', 'Boxe ringue', 'female boxer, gloves up, training ring, gritty athletic editorial, sweat', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('MMA Cage', 'Sports', 'MMA luta', 'female mma fighter, octagon cage, intense athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Jiu-Jitsu Tatami', 'Sports', 'Jiu-jitsu treino', 'female jiu-jitsu fighter, gi kimono, dojo tatami, martial arts editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Karatê Dojo', 'Sports', 'Karatê pose', 'female karate, gi white, traditional dojo, focused martial editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Muay Thai Ring', 'Sports', 'Muay thai treino', 'female muay thai fighter, traditional shorts, gym, athletic warrior editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Futebol Estádio', 'Sports', 'Futebol mulher', 'female soccer player, jersey, stadium grass, brazilian style editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Basquete Quadra', 'Sports', 'Basquete jogadora', 'female basketball player, jersey, court, dynamic athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Vôlei Praia', 'Sports', 'Vôlei praia', 'female beach volleyball, bikini sport, brazilian beach, athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Tênis Wimbledon', 'Sports', 'Tênis quadra', 'female tennis player, all-white, wimbledon court, elegant athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Golf Country Club', 'Sports', 'Golf country', 'female golfer, polo skirt, country club green, refined athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Surf Big Wave', 'Sports', 'Surf big wave', 'female big wave surfer, hawaii pipeline, dramatic ocean athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Snowboard Powder', 'Sports', 'Snowboard neve', 'female snowboarder, powder mountain, alps, action athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Ski Alpino', 'Sports', 'Ski alpino', 'female alpine skier, race suit, mountain, adrenaline athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Skate Vert', 'Sports', 'Skate vert ramp', 'female skateboarder, vert ramp, urban athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Escalada Outdoor', 'Sports', 'Escalada rocha', 'female rock climber, harness, dramatic cliff, adventure athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Trekking Patagônia', 'Sports', 'Trekking montanha', 'female trekker, patagonia mountains, backpack, adventure editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Maratona Cidade', 'Sports', 'Maratona corrida', 'female marathon runner, urban race, focused athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Triathlon Praia', 'Sports', 'Triathlon transition', 'female triathlete, swimsuit, transition zone, intense athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Ciclismo Estrada', 'Sports', 'Ciclismo road', 'female road cyclist, lycra, mountain road, athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Mountain Bike', 'Sports', 'MTB trilha', 'female mountain biker, trail, off-road action, adventure editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Natação Olímpica', 'Sports', 'Natação piscina', 'female swimmer, swim cap goggles, olympic pool, athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Mergulho Cilindro', 'Sports', 'Mergulho profundo', 'female scuba diver, coral reef, underwater athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Equitação Dressage', 'Sports', 'Equitação cavalo', 'female equestrian dressage, formal riding, horse editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Polo Match', 'Sports', 'Polo cavalo', 'female polo player, white pants, polo field, refined athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Remo Lake', 'Sports', 'Remo lago', 'female rower, scull boat, sunrise lake, athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Motocross Off-road', 'Sports', 'Motocross', 'female motocross rider, dirt bike, mud track, action athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Crossfit Box', 'Sports', 'Crossfit treino', 'female crossfit athlete, kettlebells, intense training, athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Calistenia Park', 'Sports', 'Calistenia parque', 'female calisthenics, urban park, bodyweight strength, athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Powerlifting Gym', 'Sports', 'Powerlifting peso', 'female powerlifter, deadlift, gym strength, athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Pole Dance Studio', 'Sports', 'Pole dance', 'female pole dancer, professional pole studio, athletic flexibility editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Aerial Silks', 'Sports', 'Acrobacia tecido', 'female aerial silks, circus acrobatics, ethereal athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Parkour Urban', 'Sports', 'Parkour rooftop', 'female parkour, urban rooftop, action vault, dynamic athletic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Bungee Jump', 'Sports', 'Bungee adrenaline', 'female bungee jumper, harness, dramatic cliff, adrenaline editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Paraquedismo Skydive', 'Sports', 'Paraquedismo céu', 'female skydiver, freefall, plane, sky adrenaline editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Wakeboard Lake', 'Sports', 'Wakeboard', 'female wakeboarder, lake action, athletic water editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),

-- ═══════════════════════ GAMES / COSPLAY (20) ═══════════════════════
('Cyberpunk 2077', 'Gaming', 'Cyberpunk Night City', 'cyberpunk 2077 night city, neon hacker outfit, futuristic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('GTA Vibe', 'Gaming', 'GTA street style', 'gta los santos street, urban action editorial, vivid colors', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Witcher Yennefer', 'Gaming', 'Witcher cosplay', 'witcher yennefer style, fantasy mage, gothic medieval editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Last of Us Ellie', 'Gaming', 'Last of Us', 'last of us post-apocalyptic, survivor outfit, gritty editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Anime Cosplay', 'Gaming', 'Anime convention', 'female anime cosplayer, vibrant character outfit, kawaii editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Marvel Black Widow', 'Gaming', 'Black Widow', 'black widow superhero, leather suit, action pose, marvel editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Wonder Woman DC', 'Gaming', 'Wonder Woman', 'wonder woman superhero, armor, themyscira, dramatic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Vampire Gothic', 'Gaming', 'Vampire dark', 'vampire gothic, dark castle, fangs sensual, dark fantasy editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Witch Halloween', 'Gaming', 'Bruxa halloween', 'witch halloween, black hat, autumn forest, magical editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Fairy Forest', 'Gaming', 'Fada floresta', 'fairy creature, magical forest, ethereal wings, fantasy editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Steampunk', 'Gaming', 'Steampunk vintage', 'steampunk costume, victorian goggles, industrial editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Sci-Fi Star Wars', 'Gaming', 'Sci-fi heroína', 'sci-fi heroine, futuristic armor, space fantasy editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Medieval Princess', 'Gaming', 'Princesa medieval', 'medieval princess, castle, gown, fantasy royalty editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Pirate Caribbean', 'Gaming', 'Pirata caribe', 'female pirate, caribbean ship, sword, adventure editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Western Cowgirl', 'Gaming', 'Cowgirl western', 'female cowgirl, ranch, hat boots, americana western editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Geisha Tradicional', 'Gaming', 'Gueixa Kyoto', 'traditional japanese geisha, kimono, kyoto, refined editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Samurai Warrior', 'Gaming', 'Samurai katana', 'female samurai, katana, traditional armor, japanese editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Viking Shield', 'Gaming', 'Viking guerreira', 'viking warrior, fur armor, nordic landscape, epic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Greek Goddess', 'Gaming', 'Deusa grega', 'greek goddess, white draped gown, marble columns, mythological editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Egyptian Cleopatra', 'Gaming', 'Cleópatra Egito', 'cleopatra egyptian queen, gold jewelry, dramatic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),

-- ═══════════════════════ REFERÊNCIAS CULTURAIS / DÉCADAS (20) ═══════════════════════
('Bridgerton Regency', 'Eras', 'Era Regency', 'bridgerton regency era, ball gown, candle lit ballroom, period editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Gatsby 20s', 'Eras', 'Anos 20 Gatsby', 'great gatsby 1920s, flapper sequins, art deco, jazz era editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('50s Pin-up', 'Eras', '50s pin-up', '1950s pin-up retro, polka dots, vintage americana editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('60s Mod', 'Eras', '60s mod London', '1960s mod london, mini dress, swinging sixties editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Mad Men 60s Office', 'Eras', 'Mad Men ad agency', '1960s ad agency mad men aesthetic, secretary chic, retro editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('70s Disco Studio 54', 'Eras', '70s Studio 54', '1970s disco studio 54, sequins glitter, bohemian editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('80s Madonna', 'Eras', '80s Madonna pop', '1980s madonna pop, neon, big hair, mtv era editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('80s Punk Rock', 'Eras', 'Punk 80s', '1980s punk rock, leather, mohawk, rebellion editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('90s Grunge', 'Eras', '90s grunge', '1990s grunge seattle, flannel, doc martens, alternative editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Y2K 2000s', 'Eras', 'Y2K Britney era', 'y2k 2000s britney era, low-rise, butterfly clips, mall aesthetic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Old Hollywood Glamour', 'Eras', 'Old Hollywood', 'old hollywood glamour, satin gown, film noir, classic editorial', 0, 5.0, '/placeholder.jpg', 'image', 'hard', 12),
('Frida Kahlo', 'Eras', 'Frida Kahlo style', 'frida kahlo aesthetic, traditional mexican, flowers crown, artist editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Audrey Hepburn', 'Eras', 'Audrey Hepburn', 'audrey hepburn breakfast at tiffanys, lbd, pearl elegance editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Marilyn Monroe', 'Eras', 'Marilyn Monroe', 'marilyn monroe 50s glamour, white dress, blonde curls editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Stranger Things 80s', 'Eras', 'Stranger Things', 'stranger things 80s suburbia, retro fashion, hawkins editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Euphoria HBO', 'Eras', 'Euphoria HBO', 'euphoria show aesthetic, glitter makeup, neon party editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('La Casa De Papel', 'Eras', 'Casa de Papel', 'la casa de papel money heist, red jumpsuit, dali mask editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Wednesday Addams', 'Eras', 'Wednesday Addams', 'wednesday addams gothic schoolgirl, dark academia editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Bridgerton Daphne', 'Eras', 'Daphne Bridgerton', 'daphne bridgerton blue gown, regency romance editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Barbie Movie', 'Eras', 'Barbie pink', 'barbie movie pink aesthetic, pop fashion, candy editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),

-- ═══════════════════════ AESTHETICS (15) ═══════════════════════
('Coquette Pink', 'Aesthetics', 'Coquette rosa', 'coquette aesthetic, pink ribbons, romantic feminine editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Clean Girl', 'Aesthetics', 'Clean girl bun', 'clean girl aesthetic, slick bun, gold hoops, minimalist beauty editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Tomato Girl Italian', 'Aesthetics', 'Tomato girl', 'tomato girl summer italian aesthetic, red, tomatoes, mediterranean editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Mermaidcore', 'Aesthetics', 'Mermaidcore sereia', 'mermaidcore aesthetic, sea pearls, ocean gradient, ethereal editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Balletcore', 'Aesthetics', 'Balletcore', 'balletcore aesthetic, ballet flats, pink tones, dancer editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Mob Wife', 'Aesthetics', 'Mob wife fur', 'mob wife aesthetic, fur coat, leopard, bold luxury editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Old Money Riviera', 'Aesthetics', 'Old money riviera', 'old money french riviera, linen, monaco yacht, refined editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Quiet Luxury', 'Aesthetics', 'Quiet luxury', 'quiet luxury aesthetic, neutral cashmere, refined wealth editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Hot Girl Walk', 'Aesthetics', 'Hot girl walk', 'hot girl walk aesthetic, athleisure, sunset, wellness editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('That Girl Morning', 'Aesthetics', 'That girl rotina', 'that girl morning routine, smoothie, aesthetic productivity editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Twee Indie', 'Aesthetics', 'Twee indie', 'twee indie aesthetic, vintage cardigan, books, hipster editorial', 0, 5.0, '/placeholder.jpg', 'image', 'easy', 8),
('Acubi Y2K', 'Aesthetics', 'Acubi Y2K', 'acubi aesthetic, low-rise denim, harness, edgy y2k editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Goth Dark', 'Aesthetics', 'Goth dark', 'goth dark aesthetic, all black, dramatic makeup, alternative editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Whimsigoth', 'Aesthetics', 'Whimsigoth', 'whimsigoth aesthetic, witchy bohemian, mystical editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10),
('Cottagecore Forest', 'Aesthetics', 'Cottagecore', 'cottagecore aesthetic, prairie dress, forest mushrooms, fairy editorial', 0, 5.0, '/placeholder.jpg', 'image', 'medium', 10);

-- Indexes pra busca rápida por categoria
CREATE INDEX IF NOT EXISTS idx_templates_category ON public.templates(category);
CREATE INDEX IF NOT EXISTS idx_templates_uses ON public.templates(uses_count DESC);
